spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        hbm2ddl:
          auto: update
  application:
    name: FindMyRoom
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
