spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # for normal deployment
#    url: jdbc:mysql://localhost:3306/findmytro?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true
    # for deploying by docker container
    url: jdbc:mysql://ipadress:3306/findmytro?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
  application:
    name: server
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true